# Global configuration for Prometheus
global:
  scrape_interval: 15s     # How frequently to scrape targets by default
  evaluation_interval: 15s # How frequently to evaluate rules
  scrape_timeout: 10s      # How long until a scrape request times out
  
  # Labels attached to any time series or alerts when communicating with
  # external systems (federation, remote storage, AlertManager)
  external_labels:
    monitor: 'document-management-system'
    environment: '${ENV:development}'

# Rule files specifies a list of files from which rules are read
# These contain recording rules and alerting rules
rule_files:
  - '/etc/prometheus/rules/alerts.yml'
  - '/etc/prometheus/rules/recording_rules.yml'

# Alerting specifies settings related to the AlertManager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: 'http'
      timeout: '5s'
      api_version: 'v2'

# Scrape configurations contain endpoints to scrape for metrics
scrape_configs:
  # Self-monitoring of Prometheus server
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # API Service monitoring
  - job_name: 'api_service'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 10s  # More frequent for critical service

  # Document Processor monitoring
  - job_name: 'document_processor'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/v1/metrics/document_processor'
    scrape_interval: 15s

  # Vector Search monitoring
  - job_name: 'vector_search'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/v1/metrics/vector_search'
    scrape_interval: 10s  # More frequent due to performance criticality

  # Node Exporter for host metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # PostgreSQL Exporter for database metrics
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 15s

  # Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
    scrape_interval: 15s

# Storage configuration for the time-series database
storage:
  tsdb:
    path: '/prometheus'       # Directory for storage
    retention_time: '15d'     # How long to retain data
    retention_size: '5GB'     # Maximum size of storage blocks