apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: document-management
    component: api
data:
  # Environment settings
  ENV: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  APP_NAME: "Document Management and AI Chatbot"
  API_V1_PREFIX: "/api/v1"
  
  # Database configuration
  POSTGRES_SERVER: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "document_management"
  POOL_SIZE: "10"
  MAX_OVERFLOW: "20"
  POOL_TIMEOUT: "30"
  ECHO_SQL: "false"
  
  # Vector search configuration
  VECTOR_INDEX_PATH: "/app/data/vector_indices"
  VECTOR_DIMENSION: "768"
  INDEX_TYPE: "IVFFlat"
  DEFAULT_TOP_K: "5"
  SIMILARITY_THRESHOLD: "0.7"
  NLIST: "100"
  NPROBE: "10"
  USE_GPU: "false"
  
  # LLM configuration
  LLM_MODEL: "gpt-3.5-turbo"
  TEMPERATURE: "0.7"
  MAX_TOKENS: "1024"
  CONTEXT_WINDOW_SIZE: "4000"
  REQUEST_TIMEOUT: "30"
  MAX_RETRIES: "3"
  USE_CACHE: "true"
  CACHE_TTL_SECONDS: "3600"
  
  # Document processing configuration
  DOCUMENT_STORAGE_PATH: "/app/data/documents"
  MAX_DOCUMENT_SIZE_MB: "10"
  ALLOWED_DOCUMENT_TYPES: "application/pdf"
  CHUNK_SIZE: "1000"
  CHUNK_OVERLAP: "200"
  
  # Reinforcement learning configuration
  ENABLE_FEEDBACK: "true"
  ENABLE_REINFORCEMENT_LEARNING: "true"
  FEEDBACK_BATCH_SIZE: "100"
  RL_UPDATE_FREQUENCY_HOURS: "24"
  LEARNING_RATE: "0.001"
  
  # API security and limits
  CORS_ALLOW_ORIGINS: "https://api.document-management.com"
  RATE_LIMIT_PER_MINUTE: "60"
  ALLOWED_HOSTS: "api.document-management.com"
  ENABLE_METRICS: "true"