apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: document-management
    component: api
type: Opaque
stringData:
  SECURITY_JWT_SECRET: $(JWT_SECRET)
  POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
  OPENAI_API_KEY: $(OPENAI_API_KEY)
  SECURITY_REFRESH_TOKEN_SECRET: $(REFRESH_TOKEN_SECRET)
  DATABASE_URL: postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-service:5432/document_management
  SECURITY_PASSWORD_SALT: $(PASSWORD_SALT)
  BACKUP_ENCRYPTION_KEY: $(BACKUP_ENCRYPTION_KEY)
  ADMIN_INITIAL_PASSWORD: $(ADMIN_INITIAL_PASSWORD)